language: bash

matrix:
  include:
  - os: osx
    name: "Build"
    
    script:
      - bash ./makefile.sh --VERSION=1.4.1-beta1

    deploy:
      provider: releases
      skip_clean: true
      file: "build/*.zip"
      file_glob: true
      api_key:
        secure: A+0lg2hAM22w3sWNJi4V46HemBr5ENNASOVVCcudIJAmTJiKbwAoYV4OJvq+BhtOHv5I90n5IwYguAMPa/iN1Y8xG004vZ2I+aC5k+CDTXMI7s61AiAk5pkukI5SVca2TWvwv2m8wvhvSnOzSqeuBTUe21dEAh31VWcAAu6AgNiC/D302RUhpMnUxhxWBGN3ytlPpY6bJ1qqQX87TqnaqfdbCBqeD0sjHx0OEBqn/FIZpWnTwHhdJhIyYXaYmvMbhpkpq9hsNdvgwbeZD3R9A3114auefPT+hivUMejycFcpRbjyc6cf7QPaxBv1CewfWPZj30qZ3jx1aFqSD1EynRtu1goDIiL7qWAF+PlIDRmIyl/C1c2V721m8ayD8Lh1W8N6cGUOY+JYYldnv54CKLOF2wHkvt62IVJPP4ZME3J4pMKfOS7Nsf/JZu4prLXimaiZ4C7VLPIc5lvk+r2rDgECpyWLOVHz7K7LOsg0GiqNyKI5f08Q4y+K/bap1R6SxKt3sGncrkLv1sRpl2ttQ7c+jXSgqr2letfQlYMvzyUFJWfu6mphHU8v5h/PB0/rptv/eScg7YaPho5cBL2GjAGvtXxCs1YN7F0NH+k5MAxqvWIxXP7d5HoRJvKguRe0QYZ9Qo41MB5XGDUo/LHJsejC6VdKRsON7Gt1RSFCARg=
      on:
        tags: true
